package repository

import (
	"context"
	"errors"
	"testing"

	"github.com/google/uuid"
	"github.com/stretchr/testify/require"
	"github.com/uptrace/bun"

	"github.com/sujanto-gaws/kopiochi/internal/db"
	"github.com/sujanto-gaws/kopiochi/internal/testsupport"
	domain "github.com/sujanto-gaws/kopiochi/modules/user/domain"
)

// Integration tests against a real Postgres. Not sqlmock: the SQL here is
// generated by bun, so a mocked driver would assert that bun produces the
// string the test expects rather than that the query works — it would test the
// mock (docs/architectures/06-quality/testing-strategy.md).
//
// These skip cleanly when no database is reachable. See
// testsupport.ScratchPostgres for the precedence: TEST_DATABASE_URL, then a
// disposable docker container, then skip.

// newRepo returns a repository over a migrated, empty database, plus the handle
// for seeding identities.
func newRepo(t *testing.T) (domain.Repository, *bun.DB) {
	t.Helper()

	bunDB := testsupport.MigratedDB(t)
	testsupport.TruncateAll(t, bunDB)
	return NewUserRepository(bunDB), bunDB
}

// seedIdentity inserts an auth_users row and returns its id.
//
// Raw SQL rather than identity's own repository, deliberately: R2 forbids one
// module importing another's internals, and a test is not an exemption — an
// import here would be a real dependency edge that archtest would be right to
// fail on. The profile's foreign key means a profile cannot exist without one
// of these, which is the point of the seed.
func seedIdentity(t *testing.T, bunDB *bun.DB, email string) uuid.UUID {
	t.Helper()

	id := uuid.New()
	_, err := bunDB.ExecContext(context.Background(),
		`INSERT INTO auth_users (id, username, email) VALUES (?, ?, ?)`,
		id, email, email)
	require.NoError(t, err)
	return id
}

func TestUserRepository_EnsureThenGet(t *testing.T) {
	repo, bunDB := newRepo(t)
	ctx := context.Background()
	id := seedIdentity(t, bunDB, "alice@example.com")

	require.NoError(t, repo.EnsureExists(ctx, id))

	got, err := repo.GetByID(ctx, id)
	require.NoError(t, err)
	require.Equal(t, id, got.ID, "the profile is keyed by the identity, not by a key of its own")
	require.False(t, got.CreatedAt.IsZero(), "created_at was not defaulted by the column")
	require.False(t, got.UpdatedAt.IsZero())
}

// TestUserRepository_EnsureIsIdempotent: ON CONFLICT DO NOTHING rather than a
// read-then-insert. Two concurrent first requests from one caller would race
// through a check-then-act into a duplicate-key error the second caller did
// nothing to deserve; one statement makes the idempotency the database's.
func TestUserRepository_EnsureIsIdempotent(t *testing.T) {
	repo, bunDB := newRepo(t)
	ctx := context.Background()
	id := seedIdentity(t, bunDB, "alice@example.com")

	require.NoError(t, repo.EnsureExists(ctx, id))
	first, err := repo.GetByID(ctx, id)
	require.NoError(t, err)

	require.NoError(t, repo.EnsureExists(ctx, id), "the second call must not be an error")
	second, err := repo.GetByID(ctx, id)
	require.NoError(t, err)

	require.Equal(t, first.CreatedAt, second.CreatedAt,
		"the row was recreated; the second call was not a no-op")
}

func TestUserRepository_GetMissingIsNotFound(t *testing.T) {
	repo, _ := newRepo(t)

	_, err := repo.GetByID(context.Background(), uuid.New())
	require.ErrorIs(t, err, domain.ErrUserNotFound)
}

// TestUserRepository_RefusesAProfileWithNoIdentity: the foreign key, asserted.
// An id reaching this layer came from a verified token, so an orphan should be
// unreachable — which is exactly why it is worth a constraint rather than a
// comment, and worth a test rather than trust.
func TestUserRepository_RefusesAProfileWithNoIdentity(t *testing.T) {
	repo, _ := newRepo(t)

	err := repo.EnsureExists(context.Background(), uuid.New())
	require.Error(t, err, "a profile was created for an identity that does not exist")
	require.True(t, errors.Is(err, db.ErrInvalidRef) || err != nil)
}

// TestUserRepository_ProfileDiesWithItsIdentity pins ON DELETE CASCADE. A
// profile is addressable only as the authenticated caller, so one whose
// identity is gone is unreachable — and an unreachable row that still holds a
// uuid is exactly the kind of debris a later "who is this?" query trips over.
func TestUserRepository_ProfileDiesWithItsIdentity(t *testing.T) {
	repo, bunDB := newRepo(t)
	ctx := context.Background()
	id := seedIdentity(t, bunDB, "alice@example.com")
	require.NoError(t, repo.EnsureExists(ctx, id))

	_, err := bunDB.ExecContext(ctx, `DELETE FROM auth_users WHERE id = ?`, id)
	require.NoError(t, err)

	_, err = repo.GetByID(ctx, id)
	require.ErrorIs(t, err, domain.ErrUserNotFound, "the profile outlived its identity")
}
