package repository

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/sujanto-gaws/kopiochi/internal/testsupport"
	"github.com/sujanto-gaws/kopiochi/modules/user/domain"
)

// Integration tests against a real Postgres. Not sqlmock: the SQL here is
// generated by bun, so a mocked driver would assert that bun produces the
// string the test expects rather than that the query works — it would test the
// mock (docs/architectures/06-quality/testing-strategy.md).
//
// These skip cleanly when no database is reachable. See
// testsupport.ScratchPostgres for the precedence: TEST_DATABASE_URL, then a
// disposable docker container, then skip.

// newRepo returns a repository over a migrated, empty database.
func newRepo(t *testing.T) user.Repository {
	t.Helper()

	db := testsupport.MigratedDB(t)
	testsupport.TruncateAll(t, db)
	return NewUserRepository(db)
}

func TestUserRepository_CreateThenGetByID(t *testing.T) {
	repo := newRepo(t)
	ctx := context.Background()

	u := &user.User{Name: "Alice", Email: "alice@example.com"}
	require.NoError(t, repo.Create(ctx, u))

	// Create must write the generated id back onto the entity, or the caller
	// has no way to address the row it just made.
	require.NotZero(t, u.ID, "Create did not populate the generated id")
	require.False(t, u.CreatedAt.IsZero(), "Create did not populate CreatedAt")

	got, err := repo.GetByID(ctx, u.ID)
	require.NoError(t, err)
	require.NotNil(t, got)
	require.Equal(t, "Alice", got.Name)
	require.Equal(t, "alice@example.com", got.Email)
}

// TestUserRepository_GetByIDMissingReturnsNilNil pins the contract the
// application service depends on: a missing row is (nil, nil), not an error.
// The service has explicit nil checks written against exactly this, and if the
// repository started returning sql.ErrNoRows instead they would become dead
// code while the handler received a raw driver error.
func TestUserRepository_GetByIDMissingReturnsNilNil(t *testing.T) {
	repo := newRepo(t)

	got, err := repo.GetByID(context.Background(), 999999)
	require.NoError(t, err, "a missing row must not be an error")
	require.Nil(t, got)
}

func TestUserRepository_GetByEmail(t *testing.T) {
	repo := newRepo(t)
	ctx := context.Background()

	u := &user.User{Name: "Alice", Email: "alice@example.com"}
	require.NoError(t, repo.Create(ctx, u))

	got, err := repo.GetByEmail(ctx, "alice@example.com")
	require.NoError(t, err)
	require.NotNil(t, got)
	require.Equal(t, u.ID, got.ID)
}

func TestUserRepository_GetByEmailMissingReturnsNilNil(t *testing.T) {
	repo := newRepo(t)

	got, err := repo.GetByEmail(context.Background(), "nobody@example.com")
	require.NoError(t, err)
	require.Nil(t, got)
}

// TestUserRepository_GetByEmailIsCaseSensitive records observed behaviour
// rather than asserting a wish.
//
// The column is plain text and the query is `email = ?`, so lookup is
// case-sensitive: Alice@Example.com will not find alice@example.com, and
// nothing stops both existing as separate rows. If case-insensitive identity
// is wanted, it needs a citext column or a functional index — a change to the
// schema, not to this test. Writing this down is the point; discovering it
// from a duplicate-account support ticket is the alternative.
func TestUserRepository_GetByEmailIsCaseSensitive(t *testing.T) {
	repo := newRepo(t)
	ctx := context.Background()

	require.NoError(t, repo.Create(ctx, &user.User{Name: "Alice", Email: "alice@example.com"}))

	got, err := repo.GetByEmail(ctx, "ALICE@EXAMPLE.COM")
	require.NoError(t, err)
	require.Nil(t, got, "lookup is case-sensitive; see the comment on this test")
}

func TestUserRepository_Update(t *testing.T) {
	repo := newRepo(t)
	ctx := context.Background()

	u := &user.User{Name: "Alice", Email: "alice@example.com"}
	require.NoError(t, repo.Create(ctx, u))

	u.Name = "Alice Smith"
	require.NoError(t, repo.Update(ctx, u))

	got, err := repo.GetByID(ctx, u.ID)
	require.NoError(t, err)
	require.Equal(t, "Alice Smith", got.Name)
	require.Equal(t, u.ID, got.ID, "the id must survive an update")
}

func TestUserRepository_Delete(t *testing.T) {
	repo := newRepo(t)
	ctx := context.Background()

	u := &user.User{Name: "Alice", Email: "alice@example.com"}
	require.NoError(t, repo.Create(ctx, u))

	require.NoError(t, repo.Delete(ctx, u.ID))

	got, err := repo.GetByID(ctx, u.ID)
	require.NoError(t, err)
	require.Nil(t, got, "the row is still readable after Delete")
}

// TestUserRepository_DeleteMissingRowIsNotAnError documents that the delete is
// unconditional: no rows affected is success. The application service checks
// existence first, which is what turns a wrong id into ErrUserNotFound.
func TestUserRepository_DeleteMissingRowIsNotAnError(t *testing.T) {
	repo := newRepo(t)

	require.NoError(t, repo.Delete(context.Background(), 999999))
}

// TestUserRepository_DuplicateEmailIsRejected checks whether the schema
// enforces uniqueness, which is the only place it can be enforced reliably —
// an application-level check is a race between two concurrent requests.
func TestUserRepository_DuplicateEmailIsRejected(t *testing.T) {
	repo := newRepo(t)
	ctx := context.Background()

	require.NoError(t, repo.Create(ctx, &user.User{Name: "Alice", Email: "dup@example.com"}))

	err := repo.Create(ctx, &user.User{Name: "Someone Else", Email: "dup@example.com"})
	require.Error(t, err, "two users share an email address; the users.email column has no unique constraint")
}

// TestUserRepository_TruncateAllLeavesAnEmptyTable guards the fixture itself.
// A TruncateAll that quietly did nothing would let state leak between tests
// and produce failures that look like application bugs.
func TestUserRepository_TruncateAllLeavesAnEmptyTable(t *testing.T) {
	db := testsupport.MigratedDB(t)
	repo := NewUserRepository(db)
	ctx := context.Background()

	u := &user.User{Name: "Alice", Email: "alice@example.com"}
	require.NoError(t, repo.Create(ctx, u))

	testsupport.TruncateAll(t, db)

	got, err := repo.GetByID(ctx, u.ID)
	require.NoError(t, err)
	require.Nil(t, got, "the row survived TruncateAll")
}
